name: etl-omop2phenofile
channels:
  - conda-forge
  - bioconda
  - defaults
  - anaconda
dependencies:
  - conda-forge::r-base=4.0.3
  - conda-forge::r-devtools=2.4.3
  - conda-forge::r-jsonlite=1.8.0
  - conda-forge::r-rjsonio=1.3_1.6
  - conda-forge::r-rlang=1.0.2
  - conda-forge::r-tidyverse=1.3.0
  - conda-forge::r-rjava=1.0_6

 
